name: Build & Test

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm coverage

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        if: github.ref_name == 'master'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./docs/coverage/lcov.info